// src/constants/themes.js

export const themeCursorMap = {
  light: "😊",
  dark: "🌙",
  cupcake: "🍰",
  bumblebee: "🐝",
  emerald: "🌿",
  corporate: "💼",
  synthwave: "🌸",
  retro: "📼",
  cyberpunk: "🤖",
  valentine: "💘",
  halloween: "🎃",
  garden: "🌺",
  forest: "🌳",
  aqua: "🌊",
  lofi: "🎧",
  pastel: "🍬",
  fantasy: "🧚‍♂️",
  wireframe: "✏️",
  black: "🖤",
  luxury: "💎",
  dracula: "🧛‍♂️",
  cmyk: "🎨",
  autumn: "🍂",
  business: "📈",
  acid: "☠️",
  lemonade: "🍋",
  night: "🌌",
  coffee: "☕",
  winter: "❄️",
  dim: "🌑",
  nord: "❄️",
  sunset: "🌅",
};

// src/constants/themeNames.js
export const themeNames = {
  light: "Daydream",
  dark: "Midnight Vibes",
  cupcake: "Sugar Rush",
  bumblebee: "Golden Glow",
  emerald: "Greenhouse",
  corporate: "Executive Suite",
  synthwave: "Neon Rush",
  retro: "Throwback",
  cyberpunk: "Neon Future",
  valentine: "Heartbeats",
  halloween: "Spooky Night",
  garden: "Bloom",
  forest: "Woodland Mysteries",
  aqua: "Ocean Breeze",
  lofi: "Chill Zone",
  pastel: "Cotton Candy",
  fantasy: "Dreamscape",
  wireframe: "Sketch Mode",
  black: "Blackout",
  luxury: "Golden Era",
  dracula: "Vampire's Lair",
  cmyk: "Color Splash",
  autumn: "Falling Leaves",
  business: "Power Moves",
  acid: "Neon Acid",
  lemonade: "Zesty Lemon",
  night: "Starry Night",
  coffee: "Coffee Break",
  winter: "Frozen Wonderland",
  dim: "Twilight Hour",
  nord: "Northern Lights",
  sunset: "End of Day",
};

export const moodToThemes = {
  Happy: ["light", "cupcake", "bumblebee", "synthwave", "retro", "valentine"],
  Chill: ["lofi", "pastel", "aqua", "garden", "winter", "night"],
  Inspired: ["emerald", "forest", "fantasy", "cyberpunk", "business", "nord"],
  Excited: ["synthwave", "neon", "acid", "cmyk", "dracula", "autumn"],
};
